### ISSUE TITLE
group add is not working well

### ISSUE THREAD

**Issue by wooong210** [swsnu/swpp2020-team15#108]
추가시 두 개 추가해야 둘 다 들어감.

**Comment by cheezafizz** [comment]
For me it's working well, @lgm0905 and @DOWN-LEE should check if they are too

**Comment by lgm0905** [comment]
나는 잘 돌아가는줄 알았는데 버그는 충분히있을수있어서 한번해볼게

**Comment by lgm0905** [comment]
일단 예외케이스는 확인못했고, 
empty input 처리했음
