### ISSUE TITLE
report chart : remove points that has no open price

### ISSUE THREAD

**Issue by cheezafizz** [swsnu/swpp2020-team15#117]
refer to #116

**Comment by cheezafizz** [comment]
if you oppose to this idea, please write your alternative idea down in the comment section

**Comment by lgm0905** [comment]
그래프 값들은 endprice 기준인데,
생각해보니 이거 명시해야될거같고(내가할게),
Openprice(or endprice) 값이 없는 경우는 없다고 생각해서 
일단 undefined값은 고려안했는데,
그런 경우가 있을 수 있나??

**Comment by cheezafizz** [comment]
Some stocks have times on which people couldn't make transactions.
On those times there is no open price because there weren't any transactions.

**Comment by cheezafizz** [comment]
You should doubt lines strangely parallel to x-axis, because it is very likely to be in a period of banned transaction

**Comment by lgm0905** [comment]
Implemented with add **tradevolume** in tooltip
