### ISSUE TITLE
My Interests Detail page tab change problem

### ISSUE THREAD

**Issue by lgm0905** [swsnu/swpp2020-team15#151]
My interests detail page 에서 그룹을 바꾸어도 해당 그룹에 있는 주식들이 렌더링 되지 않는 문제

**Comment by lgm0905** [comment]
#### 문제 : `component/MyPage/MyInterestsDetail/GroupStock.js`의 `React.useReducer` 부분

원인을 찾았지만 해결하기에는 지식이 부족함.
로그를 봤을 때, 각각의 그룹마다 stock정보들은 들어가 있는데,
`sortReducer` 가 문제가 있어서, 해결하는데 시간이 좀 걸릴 거라고 생각되고

그냥 sort 기능을 없애는 것도 나쁘지 않다고 생각함.
혹시 비슷한 문제를 해결한 사람이 있다면 가서 해결하면 될듯

**Comment by wooong210** [comment]
i solved it yeah
