### ISSUE TITLE
Sorting DB for fast data transfer

### ISSUE THREAD

**Issue by cheezafizz** [swsnu/swpp2020-team15#56]
Currently loading news take too much time, which results in poor user experience.

We need to sort DB for fast data transfer.

**Comment by lgm0905** [comment]
First, sorting(or any) **data processing** in backend beforehand.
Second, frontend rendering using **pagination**, or **infinity scroll**.

Above method don't imporve rendering speed dramatically,
I think alternative way is **using another DB**(MariaDB..?)

**Comment by lgm0905** [comment]
I used QuerySet.explain() to debugging, 
Following is results,

```
# News.objects.all().explain()
-> Table scan on core_news  (cost=1693.35 rows=16371) 

# News.objects.filter(stock__id = stock_id)
-> Index lookup on core_news using core_news_stock_id_57b37bfd_fk_core_stock_id (stock_id=1161)  (cost=1.40 rows=4) 

# News.objects.filter(date__year = year)
-> Filter: (core_news.`date` between '2020-01-01' and '2020-12-31')  (cost=1693.35 rows=1819)
    -> Table scan on core_news  (cost=1693.35 rows=16371)
```

So I changed `QuerySet.all()` to `Queryset.filter(stock__id == stock_id)`
