### ISSUE TITLE
About feature to delete point of the recent searches

### ISSUE THREAD

**Issue by lgm0905** [swsnu/swpp2020-team15#58]
Currently, There's no point to delete recent search.
and using `localstorage`, with key `recent-search`.

Using `sessionstorage`, it results to,
when user change window, recently searched stock is deleted. 

If you have any other ideas, please leave them in the comments.

**Comment by DOWN-LEE** [comment]
Anyway, only logged-in users can use the service, so it would not be bad to save directly to the Django model. Looking at recent searches of Naver or Google, it seems that they are saved directly to the DB instead of saving them to the session.

**Comment by lgm0905** [comment]
In fact, doing so makes it clear when it comes to dealing with constant-search.
It would be better to calculate the time roughly through which parts should be corrected and if it is deemed reasonable.
I think we should all talk about this part together!

**Comment by cheezafizz** [comment]
We'll talk about this on the following meeting on Thursday, please don't forget to mention this issue during the meeting, @lgm0905
