### ISSUE TITLE
Revisement of overall designs

### ISSUE THREAD

**Issue by cheezafizz** [swsnu/swpp2020-team15#72]
Our current UI design is not the worst, but also not the best.

Let's list out some design related hazards existing currently.

**Comment by cheezafizz** [comment]
- Candlestick chart in Detail Page
- My Information in My Page

**Comment by lgm0905** [comment]
Detailpage 편집 버튼
Reportpage stockblock 뉴스 왼쪽정렬
MyPage myinformation 버튼 개선

**Comment by wooong210** [comment]
mypage grid 개선

**Comment by wooong210** [comment]
mypage 편집 버튼이 그룹 탭에 들어가면 좋을듯 이건 내가 하겠ㅇ

**Comment by wooong210** [comment]
myinterest에도 편집 버튼이 있으면 좋지 않을까

**Comment by wooong210** [comment]
detailpricetrend 에 data.length 로 확인 전에  data 있는지 확인하기

**Comment by lgm0905** [comment]
Detailpage news datepicker, list 개선

**Comment by wooong210** [comment]
comment 예쁘게 만들기

**Comment by wooong210** [comment]
signout 버튼 information tab에 넣기

**Comment by wooong210** [comment]
find password 에 1 2 지우기

**Comment by wooong210** [comment]
forget password 와 버튼 사이 띄우기

**Comment by wooong210** [comment]
찜 eye
해결 폭죽

**Comment by wooong210** [comment]
finish all
