### ISSUE TITLE
input field submit with enter

### ISSUE THREAD

**Issue by wooong210** [swsnu/swpp2020-team15#86]
로그인이나 회원가입 등의 input field에서 엔터키로 제출할 수 있는 기능이 있으면 좋을 듯.

( 어려울 것 같지만 searchBox에서 검색 결과가 하나일 때 엔터 눌러서 넘어가는 것도 좋을 것 같음)

**Comment by lgm0905** [comment]
내가 알기론 서치박스에서 기본적으로 아이템들이 선택되지는 않고, 키보드 화살표 눌러서 선택후 엔터누르면 리다이렉트는 되는걸로 알고있음

**Comment by cheezafizz** [comment]
consensus on abandoning this issue ( low - priority )
